"""Add PointRequest model

Revision ID: 12c5b62b094c
Revises: 33845d2aac0d
Create Date: 2025-11-18 12:04:47.359019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12c5b62b094c'
down_revision = '33845d2aac0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('POINT_REQUESTS',
    sa.Column('REQUEST_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('DRIVER_ID', sa.Integer(), nullable=False),
    sa.Column('ORG_ID', sa.Integer(), nullable=False),
    sa.Column('POINTS', sa.Integer(), nullable=False),
    sa.Column('REASON', sa.String(length=255), nullable=False),
    sa.Column('STATUS', sa.String(length=20), nullable=False),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['DRIVER_ID'], ['DRIVERS.DRIVER_ID'], ),
    sa.ForeignKeyConstraint(['ORG_ID'], ['ORGANIZATIONS.ORG_ID'], ),
    sa.PrimaryKeyConstraint('REQUEST_ID')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('IMPERSONATION_LOG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ACTION', mysql.VARCHAR(length=20), nullable=False, comment='start or stop'))
        batch_op.add_column(sa.Column('TARGET_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('CREATED_AT', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('ACTOR_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('IMPERSONATION_TARGET_FK'), ['TARGET_ID'], unique=False)
        batch_op.create_index(batch_op.f('IMPERSONATION_ACTOR_FK'), ['ACTOR_ID'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('action')
        batch_op.drop_column('target_id')
        batch_op.drop_column('actor_id')

    with op.batch_alter_table('DRIVER_APPLICATIONS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RESPONDED_AT', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('SPONSOR_RESPONSIBLE_ID', mysql.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('POINT_REQUESTS')
    # ### end Alembic commands ###
