"""Add ORG_ID to CART_ITEMS table

Revision ID: 33845d2aac0d
Revises: 7a9e3b5c2d1f
Create Date: 2025-11-10 08:24:42.174701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33845d2aac0d'
down_revision = '7a9e3b5c2d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CART_ITEMS', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('CART_ITEMS_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ORGANIZATIONS', ['ORG_ID'], ['ORG_ID'])

    with op.batch_alter_table('DRIVER_APPLICATIONS', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ORGANIZATIONS', ['ORG_ID'], ['ORG_ID'], ondelete='CASCADE')

    with op.batch_alter_table('DRIVER_SPONSOR_ASSOCIATION', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'DRIVERS', ['driver_id'], ['DRIVER_ID'])

    with op.batch_alter_table('EMAIL_2FA_CODE', schema=None) as batch_op:
        batch_op.alter_column('sent_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('attempts',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_foreign_key(None, 'USERS', ['user_id'], ['USER_CODE'])

    with op.batch_alter_table('SPONSORS', schema=None) as batch_op:
        batch_op.alter_column('ORG_ID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_sponsor_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sponsor_organization'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ORGANIZATIONS', ['ORG_ID'], ['ORG_ID'])
        batch_op.create_foreign_key(None, 'USERS', ['USER_CODE'], ['USER_CODE'])

    with op.batch_alter_table('STORE_SETTINGS', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_settings_organization'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ORGANIZATIONS', ['ORG_ID'], ['ORG_ID'])

    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.alter_column('wants_security_notifications',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('EMAIL_VERIFIED',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('EMAIL_2FA_ENABLED',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.alter_column('EMAIL_2FA_ENABLED',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('EMAIL_VERIFIED',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('wants_security_notifications',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('STORE_SETTINGS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_settings_organization'), 'ORGANIZATIONS', ['ORG_ID'], ['ORG_ID'], ondelete='CASCADE')

    with op.batch_alter_table('SPONSORS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sponsor_organization'), 'ORGANIZATIONS', ['ORG_ID'], ['ORG_ID'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_sponsor_user'), 'USERS', ['USER_CODE'], ['USER_CODE'], ondelete='CASCADE')
        batch_op.alter_column('ORG_ID',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('IMPERSONATION_LOG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ACTION', mysql.VARCHAR(length=20), nullable=False, comment='start or stop'))
        batch_op.add_column(sa.Column('CREATED_AT', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('TARGET_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ACTOR_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('IMPERSONATION_ACTOR_FK'), 'USERS', ['ACTOR_ID'], ['USER_CODE'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('IMPERSONATION_TARGET_FK'), 'USERS', ['TARGET_ID'], ['USER_CODE'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('created_at')
        batch_op.drop_column('action')
        batch_op.drop_column('target_id')
        batch_op.drop_column('actor_id')

    with op.batch_alter_table('EMAIL_2FA_CODE', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_email2fa_user'), 'USERS', ['user_id'], ['USER_CODE'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_EMAIL_2FA_CODE_user_id'))
        batch_op.alter_column('attempts',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sent_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('DRIVER_SPONSOR_ASSOCIATION', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_dsa_driver'), 'USERS', ['driver_id'], ['USER_CODE'])

    with op.batch_alter_table('DRIVER_APPLICATIONS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_application_organization'), 'ORGANIZATIONS', ['ORG_ID'], ['ORG_ID'], ondelete='RESTRICT')

    with op.batch_alter_table('CART_ITEMS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsor_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('CART_ITEMS_ibfk_2'), 'SPONSORS_OLD', ['sponsor_id'], ['SPONSOR_ID'])
        batch_op.drop_column('ORG_ID')

    op.create_table('SPONSORS_OLD',
    sa.Column('SPONSOR_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ORG_NAME', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('STATUS', mysql.ENUM('Pending', 'Approved', 'Rejected'), server_default=sa.text("'Pending'"), nullable=True),
    sa.ForeignKeyConstraint(['SPONSOR_ID'], ['USERS.USER_CODE'], name=op.f('SPONSORS_OLD_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SPONSOR_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('STORE_SETTINGS_OLD',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sponsor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ebay_category_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('point_ratio', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['SPONSORS_OLD.SPONSOR_ID'], name=op.f('STORE_SETTINGS_SPONSORS_FK')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('STORE_SETTINGS_OLD', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sponsor_id'), ['sponsor_id'], unique=True)

    op.create_table('DRIVER_SPONSOR_ASSOCIATION_OLD',
    sa.Column('driver_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sponsor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['DRIVERS.DRIVER_ID'], name=op.f('DRIVER_SPONSOR_ASSOCIATION_OLD_ibfk_1')),
    sa.ForeignKeyConstraint(['sponsor_id'], ['SPONSORS_OLD.SPONSOR_ID'], name=op.f('DRIVER_SPONSOR_ASSOCIATION_OLD_ibfk_2')),
    sa.PrimaryKeyConstraint('driver_id', 'sponsor_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    
    # ### end Alembic commands ###
