"""Add WeeklyPointsLog table

Revision ID: bc4e2b6d78fe
Revises: 12c5b62b094c
Create Date: 2025-11-25 12:13:59.813372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc4e2b6d78fe'
down_revision = '12c5b62b094c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WEEKLY_POINTS_LOG',
    sa.Column('LOG_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SPONSOR_ID', sa.Integer(), nullable=False),
    sa.Column('DRIVER_ID', sa.Integer(), nullable=False),
    sa.Column('POINTS', sa.Integer(), nullable=False),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['DRIVER_ID'], ['USERS.USER_CODE'], ),
    sa.ForeignKeyConstraint(['SPONSOR_ID'], ['USERS.USER_CODE'], ),
    sa.PrimaryKeyConstraint('LOG_ID')
    )
    with op.batch_alter_table('DRIVER_APPLICATIONS', schema=None) as batch_op:
        batch_op.alter_column('RESPONDED_AT',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'USERS', ['SPONSOR_RESPONSIBLE_ID'], ['USER_CODE'])

    with op.batch_alter_table('IMPERSONATION_LOG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('action', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f('IMPERSONATION_ACTOR_FK'))
        batch_op.drop_index(batch_op.f('IMPERSONATION_TARGET_FK'))
        batch_op.create_foreign_key(None, 'USERS', ['target_id'], ['USER_CODE'])
        batch_op.create_foreign_key(None, 'USERS', ['actor_id'], ['USER_CODE'])
        batch_op.drop_column('ACTION')
        batch_op.drop_column('ACTOR_ID')
        batch_op.drop_column('TARGET_ID')
        batch_op.drop_column('CREATED_AT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('IMPERSONATION_LOG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CREATED_AT', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('TARGET_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ACTOR_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ACTION', mysql.VARCHAR(length=20), nullable=False, comment='start or stop'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('IMPERSONATION_TARGET_FK'), ['TARGET_ID'], unique=False)
        batch_op.create_index(batch_op.f('IMPERSONATION_ACTOR_FK'), ['ACTOR_ID'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('action')
        batch_op.drop_column('target_id')
        batch_op.drop_column('actor_id')

    with op.batch_alter_table('DRIVER_APPLICATIONS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('RESPONDED_AT',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)

    op.drop_table('WEEKLY_POINTS_LOG')
    # ### end Alembic commands ###
